//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FiorentinoForm.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class estoque
    {
        public int id { get; set; }
        public Nullable<int> produtoId { get; set; }
        public Nullable<int> lojaId { get; set; }
        public Nullable<int> quantidade { get; set; }
    
        public virtual loja loja { get; set; }
        public virtual produto produto { get; set; }
    }
}
