//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FiorentinoForm.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MobileALEntities : DbContext
    {
        public MobileALEntities()
            : base("name=MobileALEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<cidade> cidade { get; set; }
        public virtual DbSet<estado> estado { get; set; }
        public virtual DbSet<estoque> estoque { get; set; }
        public virtual DbSet<evento> evento { get; set; }
        public virtual DbSet<loja> loja { get; set; }
        public virtual DbSet<participante> participante { get; set; }
        public virtual DbSet<participantes_evento> participantes_evento { get; set; }
        public virtual DbSet<produto> produto { get; set; }
        public virtual DbSet<regiao> regiao { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<tipo_evento> tipo_evento { get; set; }
        public virtual DbSet<vendas> vendas { get; set; }
    }
}
