//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FiorentinoForm.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class participantes_evento
    {
        public int id { get; set; }
        public Nullable<int> eventoId { get; set; }
        public Nullable<int> participanteId { get; set; }
    
        public virtual evento evento { get; set; }
        public virtual participante participante { get; set; }
    }
}
